import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingChat from "@/components/FloatingChat";
import DesignCard from "@/components/DesignCard";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { useLocation } from "wouter";
import { useEffect, useState } from "react";
import { X } from "lucide-react";


import bedroomImage from '@assets/generated_images/Bedroom_category_showcase_d4e96a70.png';
import kitchenImage from '@assets/generated_images/Kitchen_category_showcase_bf36e66d.png';
import bathroomImage from '@assets/generated_images/Bathroom_category_showcase_780b4e76.png';
import livingRoomImage from '@assets/generated_images/Hero_living_room_interior_730dd1ef.png';
import diningImage from '@assets/generated_images/Dining_room_product_66c8c369.png';
import scandinavianImage from '@assets/generated_images/Designer_portfolio_scandinavian_0f0672da.png';

export default function Gallery() {
  const [location, setLocation] = useLocation();
  
  // Initialize activeTab from URL on page load
  const getTabFromUrl = () => {
    const params = new URLSearchParams(window.location.search);
    return params.get("tab") || "all";
  };
  
  const [activeTab, setActiveTab] = useState(getTabFromUrl());
  const [selectedDesign, setSelectedDesign] = useState<{
    imageSrc: string;
    title: string;
    category?: string;
    description?: string;
  } | null>(null);

  useEffect(() => {
    setActiveTab(getTabFromUrl());
  }, [location]);

  const designs = {
    all: [
      { imageSrc: "/living room/40 Neutral Sitting Room Ideas To Create a Calm, Cozy Space.jpg", title: "Neutral Calm Cozy Sitting Room", description: "Experience the epitome of tranquility with this neutral-toned sitting room designed to create a calm and inviting atmosphere. The carefully curated color palette of soft beiges, warm creams, and gentle grays creates a soothing environment perfect for relaxation and unwinding. Features plush upholstered seating with deep cushions, layered textiles including throw pillows and cozy blankets, and natural materials like jute rugs and wooden accents. Ambient lighting from table lamps and floor lamps creates warm pools of light, while sheer curtains filter natural light softly. The space includes smart storage solutions hidden within elegant furniture pieces, maintaining the uncluttered aesthetic essential to a peaceful retreat. Thoughtful accessories like potted plants, artwork in muted tones, and decorative objects add personality without overwhelming the serene vibe. Perfect for those seeking a peaceful sanctuary away from the chaos of daily life." },
      { imageSrc: "/living room/58 Luxury Modern Homes for High-End Living.jpg", title: "Ultra-Luxury Modern High-End Living Room", description: "Step into the world of ultra-luxury with this breathtaking modern living room that defines high-end contemporary living. This showcase of opulence features soaring ceilings with architectural details, floor-to-ceiling windows offering panoramic views, and a color palette of sophisticated neutrals with metallic accents. Premium materials include Italian marble flooring, designer furniture from renowned brands, and custom millwork with impeccable craftsmanship. The space showcases statement lighting fixtures including modern chandeliers and recessed LED systems, creating dramatic ambiance. Includes a state-of-the-art entertainment system seamlessly integrated into the design, automated smart home features controlling lighting and climate, and luxurious textiles like silk drapery and velvet upholstery. Architectural elements such as feature walls with textured finishes, floating staircases, and open-concept layouts enhance the sense of grandeur. Perfect for discerning homeowners who appreciate the finest in modern luxury living." },
      { imageSrc: "/living room/download (1).jpg", title: "Contemporary Elegance Living Space", description: "Discover refined contemporary design in this elegantly appointed living space that balances modern aesthetics with comfortable functionality. The room features clean architectural lines, a sophisticated color scheme of charcoal, white, and warm wood tones, and carefully selected designer furniture pieces. Key elements include a plush sectional sofa positioned for conversation and TV viewing, sleek entertainment center with integrated storage, and accent chairs that add visual interest. The design incorporates layered lighting with recessed ceiling fixtures, modern pendant lights, and task lighting for reading areas. Contemporary artwork and sculptural accessories serve as focal points, while textured area rugs define seating zones. Large windows are dressed with modern window treatments that provide privacy while maximizing natural light. Smart organization solutions keep the space clutter-free and serene. This design is ideal for modern families or professionals seeking a stylish yet livable space." },
      { imageSrc: "/living room/download (2).jpg", title: "Refined Modern Living Room Design", description: "Experience the perfect blend of modern design principles and everyday comfort in this refined living room. The space features an open layout that promotes flow and conversation, with a neutral foundation enhanced by carefully chosen accent colors. Design highlights include a contemporary fireplace serving as a stunning focal point, built-in shelving for display and storage, and furniture with clean lines and comfortable proportions. The material palette combines natural wood, soft textiles, metal accents, and glass elements for visual variety. Thoughtful details include crown molding and architectural trim, hardwood or luxury vinyl flooring, and large-scale artwork that adds personality. The lighting scheme layers ambient, task, and accent lighting to create the perfect mood for any occasion. Window treatments frame views while controlling light and privacy. This versatile design works beautifully for entertaining guests or relaxing with family." },
      { imageSrc: "/kitchen/kitchen1.jpg", title: "Pristine Pearl White U-Shaped Modular Kitchen", description: "Immerse yourself in the timeless elegance of this pristine pearl white U-shaped modular kitchen, where form meets function in perfect harmony. This stunning kitchen design features floor-to-ceiling white cabinetry with soft-close mechanisms, creating a bright and spacious atmosphere that makes cooking a joy. The U-shaped layout maximizes efficiency with the classic work triangle positioning the sink, stove, and refrigerator for optimal workflow. Premium features include quartz or marble countertops that resist stains and scratches, stainless steel appliances for a cohesive modern look, and sleek handleless cabinets with push-to-open technology. Thoughtful details like under-cabinet LED lighting illuminate work surfaces, while a large window brings natural light flooding in. Smart storage solutions include pull-out pantry units, corner carousel systems, and deep drawers for pots and pans. The pristine white finish is complemented by chrome fixtures and subtle gray veining in the countertops. Perfect for families who love to cook and entertain, this kitchen combines beauty with unparalleled functionality." },
      { imageSrc: "/kitchen/kitchen2.jpg", title: "Warm Ecru Elegance L-Shaped Modular Kitchen", description: "Welcome to warmth and sophistication with this elegant ecru-toned L-shaped modular kitchen that brings a touch of refined luxury to your home. The soft ecru cabinetry creates an inviting atmosphere while maintaining a contemporary aesthetic, perfectly complemented by warm wood accents and brushed gold hardware. The L-shaped configuration is ideal for medium-sized spaces, providing ample counter space and storage while maintaining an open, airy feel. Premium appointments include composite stone countertops in complementary tones, high-quality built-in appliances seamlessly integrated into the cabinetry, and a stylish backsplash featuring textured tiles or glass panels. Innovative features include soft-close drawers with organizational inserts, a dedicated spice pull-out rack, and corner cabinets with rotating shelves for easy access. The warm color palette is enhanced by strategically placed lighting including pendant lights over the counter and LED strips under cabinets. This kitchen design is perfect for those who appreciate understated elegance and want a space that feels both sophisticated and welcoming." },
      { imageSrc: "/kitchen/kitchen3.jpg", title: "Gainsboro Grace U-Shaped Island Kitchen", description: "Experience culinary luxury in this graceful Gainsboro gray U-shaped kitchen with a stunning central island that serves as the heart of the home. The sophisticated gray cabinetry provides a modern, upscale look while the warm undertones prevent the space from feeling cold or sterile. The U-shaped perimeter offers maximum storage and counter space, while the central island provides additional prep area, casual dining, and social interaction space. Premium features include a waterfall-edge island countertop showcasing beautiful stone veining, professional-grade appliances for serious cooking enthusiasts, and custom cabinetry with varied heights and depths for visual interest. The island includes seating for 3-4 people with comfortable bar stools, hidden storage compartments, and potential for a prep sink or wine cooler. Designer touches include statement pendant lights over the island, a pot filler faucet at the cooktop, and open shelving to display beautiful dishes or cookbooks. The cohesive design is completed with premium hardware, a designer range hood, and luxury flooring. Ideal for homeowners who love to cook and entertain, making the kitchen the social hub of the home." },
      { imageSrc: "/kitchen/kitchen4.jpg", title: "Coastal Breeze Straight Island Kitchen", description: "Bring the relaxed elegance of coastal living into your home with this bright and breezy straight island kitchen design. Inspired by beachside retreats, this kitchen features a light and airy color palette of soft whites, pale blues, and natural wood tones that evoke seaside serenity. The straight island layout is perfect for creating an open, flowing space that connects to adjacent living areas, making it ideal for open-concept homes. Coastal design elements include shiplap or beadboard accents, glass-front upper cabinets to display beach-inspired dishware, and nautical-themed hardware like rope pulls or anchor motifs. The island serves multiple purposes with its extended countertop for dining, storage cabinets below, and potential for a farmhouse sink or beverage station. Premium features include durable quartz countertops that resist moisture and stains, white or light wood cabinetry with a slightly distressed finish for character, and stainless or white appliances that maintain the fresh, clean aesthetic. Natural light is maximized through large windows dressed with light, flowing curtains. Perfect for those who want to capture the relaxed, breezy feel of coastal living year-round." },
      { imageSrc: "/bedroom/bedroom.jpg", title: "Serene Sanctuary Master Bedroom", description: "Retreat to your personal haven with this serene sanctuary master bedroom designed for ultimate relaxation and rejuvenation. The thoughtfully designed space creates a peaceful atmosphere through a carefully chosen neutral color palette, luxurious textiles, and ambient lighting. Premium features include a plush upholstered headboard that serves as a stunning focal point, high-quality bedding with layered textures including duvet, throws, and decorative pillows, and bedside tables with integrated lighting and charging stations. The room incorporates blackout curtains or shades for optimal sleep conditions, soft area rugs for warmth and comfort underfoot, and artwork that promotes tranquility. Smart storage solutions include a spacious walk-in closet or built-in wardrobes, under-bed storage for seasonal items, and elegant dressers or armoires. Ambient lighting features dimmer switches for mood control, bedside reading lamps, and potentially a statement ceiling fixture. Modern conveniences might include a wall-mounted TV with concealed wiring, a cozy reading nook with comfortable seating, and climate control for year-round comfort. This master bedroom design is perfect for homeowners seeking a luxurious retreat that promotes restful sleep and peaceful mornings." },
      { imageSrc: "/bedroom/bedroom1.jpg", title: "Contemporary Urban Bedroom Suite", description: "Embrace modern city living with this contemporary urban bedroom suite that combines sleek design with sophisticated comfort. The space features clean lines, geometric patterns, and a refined color scheme of grays, blacks, and whites with occasional metallic accents. Design highlights include a low-profile platform bed with integrated storage or lighting, floating nightstands for a modern minimalist look, and a streamlined dresser or chest with handleless design. Urban sophistication is achieved through industrial-inspired elements like exposed brick or concrete accent walls, modern artwork featuring cityscapes or abstract designs, and metal-framed mirrors or decorative pieces. Lighting plays a crucial role with recessed LED ceiling lights, contemporary pendant lights or wall sconces, and possibly LED strip lighting for ambient effects. Premium materials include hardwood or luxury vinyl plank flooring, high-quality linens in solid colors or subtle patterns, and textured accent walls or wallpaper. Smart home features might include automated blinds, voice-controlled lighting, and integrated sound systems. This design is ideal for young professionals or modern couples who appreciate contemporary aesthetics and urban sophistication." },
      { imageSrc: "/bedroom/bedroom2.webp", title: "Classic Elegance Bedroom Design", description: "Step into timeless beauty with this classic elegance bedroom that showcases traditional design principles while incorporating modern comfort. The room features traditional furniture with refined details including a four-poster or upholstered sleigh bed as the centerpiece, matching nightstands with drawer storage and lamp space, and a coordinating dresser and mirror set. Classic elegance is expressed through rich wood tones in cherry, mahogany, or walnut finishes, traditional molding and trim details including crown molding and baseboards, and elegant window treatments with valances or swags. The color palette typically includes warm neutrals, deep jewel tones, or soft pastels, creating a sophisticated and inviting atmosphere. Luxurious textiles feature high-thread-count sheets, decorative bed skirts, and coordinated window treatments. Traditional accessories include classic table lamps with fabric shades, framed artwork or family photos, and tasteful decorative objects. Modern updates ensure comfort with quality mattresses, adequate electrical outlets and USB ports, and efficient climate control. This bedroom design appeals to those who appreciate traditional craftsmanship and enduring style." },
      { imageSrc: "/bedroom/bedroom3.jpg", title: "Modern Minimalist Bedroom Retreat", description: "Discover the beauty of simplicity in this modern minimalist bedroom retreat where less truly becomes more. This design philosophy embraces clean lines, uncluttered spaces, and a 'quality over quantity' approach to furnishings and decor. The essential elements include a simple platform bed with clean lines and no ornate details, minimal nightstands or floating shelves for bedside essentials, and a streamlined wardrobe or closet system that keeps belongings hidden. The minimalist aesthetic features a restricted color palette of typically 2-3 colors (often white, gray, and one accent), smooth surfaces without excessive texture or pattern, and carefully edited decor with each piece serving a purpose. Storage solutions are cleverly concealed within built-in cabinets and drawers, under-bed storage systems, and multi-functional furniture pieces. Lighting is simple yet effective with recessed or track lighting, simple pendant lights or wall sconces, and maximized natural light through unobstructed windows. The floor plan maintains open space for easy movement and a sense of calm. Perfect for those who find peace in simplicity and want a bedroom free from visual clutter." },
      { imageSrc: "/bathroom/bathroom.webp", title: "Luxe Spa Master Bathroom", description: "Transform your daily routine into a spa-like experience with this luxurious master bathroom. Features premium Italian marble tiles, a freestanding soaking tub, rainfall shower with body jets, and heated floors. The design includes floating double vanities with LED-backlit mirrors, soft-close drawers with smart organizational inserts, and ambient lighting that creates a serene atmosphere. Premium fixtures in brushed gold or chrome finish add elegance, while the neutral color palette of whites, grays, and natural stone creates a timeless look. Perfect for homeowners seeking a personal wellness retreat." },
      { imageSrc: "/bathroom/bathroom1.webp", title: "Modern Minimalist Sanctuary", description: "Embrace clean lines and simplicity in this modern minimalist bathroom. The design features wall-mounted vanities creating a floating effect, frameless glass shower enclosure, and seamless large-format porcelain tiles that minimize grout lines. Includes concealed storage solutions, touch-free faucets, and integrated LED lighting strips. The monochromatic color scheme with subtle texture variations creates visual interest while maintaining serenity. Features include anti-fog mirror technology, underfloor heating, and eco-friendly water-saving fixtures. Ideal for contemporary homes that value both aesthetics and functionality." },
      { imageSrc: "/bathroom/bathroom2.jpg", title: "Classic Victorian Elegance", description: "Step back in time with this Victorian-inspired bathroom that combines old-world charm with modern convenience. Features include a clawfoot bathtub with antique brass fixtures, pedestal sink with ornate detailing, and vintage-style subway tiles with decorative borders. The design incorporates crown molding, wainscoting, and classic hexagonal floor tiles. Modern amenities include concealed plumbing, efficient ventilation, and updated lighting while maintaining period authenticity. Rich wood tones and crystal chandelier add warmth and sophistication. Perfect for heritage homes or those who appreciate timeless classical design." },
      { imageSrc: "/bathroom/bathroom3.jpg", title: "Contemporary Zen Retreat", description: "Find peace and tranquility in this Zen-inspired contemporary bathroom. The design features natural materials including teak wood accents, river stone flooring, and bamboo elements. Includes a deep Japanese-style soaking tub, walk-in rain shower with pebble floor, and minimalist floating vanity. Natural light is maximized through frosted glass and skylights. Features include waterfall faucets, live plants, and neutral earth tones that promote relaxation. The layout emphasizes clean lines, uncluttered spaces, and natural textures. Ideal for those seeking a meditative bathing experience and connection with nature." },
      { imageSrc: "/wardrobe/12 Wardrobe Design Bedroom Modern Luxury Ideas for___.jpg", title: "Modern Luxury Wardrobe Collection", description: "Experience ultimate organization and luxury with this modern wardrobe design featuring sleek handleless doors, premium finishes, and innovative storage solutions. The design includes floor-to-ceiling cabinetry that maximizes vertical space, soft-close mechanisms, and LED interior lighting for easy visibility. Premium materials feature high-gloss laminates, mirror panels, and integrated accessories like pull-out drawers, jewelry organizers, and shoe racks. Modern conveniences include smart lighting sensors, climate control for delicate garments, and customizable shelving systems. The contemporary aesthetic with clean lines creates a sophisticated bedroom focal point. Perfect for those seeking a luxury boutique experience at home with ample storage and impeccable organization." },
      { imageSrc: "/wardrobe/Add Touch Of Elegance To Your Bedroom With This Wardrobe Collection.jpg", title: "Elegant Bedroom Wardrobe Collection", description: "Add a touch of timeless elegance to your bedroom with this sophisticated wardrobe collection. Features classic design elements including raised panel doors, ornate handles in antique finishes, and quality wood veneers. The design includes multiple hanging sections for different garment lengths, spacious drawers with velvet lining, and open shelving for folded items. Premium appointments feature soft-close hinges, adjustable shelves, and integrated tie and belt racks. Traditional craftsmanship meets modern functionality with proper ventilation, interior lighting, and modular configurations. The refined aesthetic complements both traditional and transitional bedroom styles. Ideal for those who appreciate classical elegance combined with practical storage solutions." },
      { imageSrc: "/wardrobe/download (1).jpg", title: "Contemporary Sliding Door Wardrobe", description: "Maximize space efficiency with this contemporary sliding door wardrobe perfect for modern bedrooms. Features smooth-gliding door systems that save floor space, clean minimalist profiles, and quality materials. The design includes versatile interior layouts with hanging rods at multiple heights, pull-out drawers, and modular shelf systems. Modern elements feature soft-close mechanisms, full-length mirrors on doors, and optional LED lighting. Premium finishes available in matte, gloss, or wood grain laminates to match any decor. The space-saving design makes it ideal for smaller bedrooms while providing ample storage. Perfect for contemporary homes seeking functionality without compromising on style." },
      { imageSrc: "/wardrobe/download (2).jpg", title: "Walk-In Closet Wardrobe System", description: "Transform your bedroom into a luxury boutique with this walk-in closet wardrobe system. Features comprehensive organization including double hanging sections, dedicated shoe storage, accessory drawers, and display shelving. The design includes a central island with jewelry storage, pull-out trouser racks, and dedicated handbag shelves. Premium appointments feature velvet-lined drawers, LED strip lighting throughout, full-length mirrors, and optional seating area. Modern conveniences include motion-sensor lighting, climate control options, and customizable layouts. The boutique-like atmosphere with elegant finishes creates a dressing room experience. Ideal for luxury homes with space for dedicated walk-in closets and extensive wardrobes." },
    ],
    living: [
      { imageSrc: "/living room/40 Neutral Sitting Room Ideas To Create a Calm, Cozy Space.jpg", title: "Neutral Calm Cozy Sitting Room", description: "Create a serene sanctuary with this neutral sitting room design that epitomizes calm and comfort. Features soft beige and cream color palette, plush upholstered sofas with deep seating, and layered textiles including throws and cushions for warmth. The design includes natural fiber rugs, wooden coffee tables with organic shapes, and ambient lighting with table lamps and floor lamps. Premium elements feature quality linen curtains, textured wall treatments, and carefully curated artwork. Modern conveniences include hidden storage solutions, smart lighting controls, and cable management systems. The neutral tones create a peaceful backdrop while various textures add depth and interest. Perfect for those seeking a relaxing, sophisticated living space that promotes conversation and comfort." },
      { imageSrc: "/living room/58 Luxury Modern Homes for High-End Living.jpg", title: "Ultra-Luxury Modern High-End Living Room", description: "Experience the pinnacle of luxury in this stunning modern living room designed for high-end living. Features floor-to-ceiling windows with panoramic views, designer furniture from renowned brands, and premium materials including marble, leather, and exotic woods. The design showcases statement lighting fixtures, custom built-in entertainment centers, and sophisticated color schemes with metallic accents. Premium appointments include smart home integration, motorized window treatments, premium sound systems, and climate control. Art collection-worthy spaces with gallery lighting, sculptural furniture pieces, and bespoke accessories. The open-plan layout maximizes space and light while maintaining intimate seating areas. Ideal for discerning homeowners who demand uncompromising luxury and cutting-edge design." },
      { imageSrc: "/living room/download (1).jpg", title: "Contemporary Elegance Living Space", description: "Embrace modern sophistication in this contemporary living room that balances style and comfort perfectly. Features clean-lined furniture with refined proportions, neutral color palette with strategic accent colors, and quality materials throughout. The design includes floating media consoles, sleek coffee tables with glass or metal accents, and comfortable seating arrangements. Modern elements feature recessed lighting, minimalist window treatments, and polished surfaces. Premium touches include designer light fixtures, curated decorative objects, and high-end finishes. The layout promotes natural flow and conversation while maintaining visual interest through varied textures and forms. Perfect for modern homes seeking timeless contemporary elegance and functionality." },
      { imageSrc: "/living room/download (2).jpg", title: "Warm Modern Family Living Room", description: "Gather in comfort in this warm modern living room designed for family life. Features durable yet stylish furniture, comfortable sectional sofas perfect for lounging, and kid-friendly materials that don't sacrifice style. The design includes smart storage solutions with built-in cabinets, ottoman storage, and media organization. Family-focused elements feature open layouts for supervision, easy-to-clean surfaces, and flexible seating arrangements. Modern conveniences include entertainment systems, charging stations, and proper task lighting for activities. Warm color schemes with inviting textures create a cozy atmosphere. The practical yet beautiful design accommodates both daily living and entertaining. Ideal for active families seeking style and durability." },
      { imageSrc: "/living room/download (3).jpg", title: "Scandinavian Minimalist Living Room", description: "Discover Nordic simplicity in this beautiful Scandinavian living room that celebrates functional minimalism. Features light wood furniture, white or light gray walls, and clean architectural lines. The design emphasizes natural light through large windows with simple treatments, indoor plants for freshness, and carefully selected decorative items. Premium elements include quality textiles in natural fibers, iconic Scandinavian design pieces, and efficient storage that disappears into walls. Modern practicality features energy-efficient lighting, sustainable materials, and multi-functional furniture. The bright, airy atmosphere promotes well-being and clarity. Perfect for those who appreciate understated elegance and functional beauty in the Scandinavian tradition." },
      { imageSrc: "/living room/download (4).jpg", title: "Industrial Chic Urban Loft Living", description: "Make a bold statement with this industrial-chic living room perfect for urban loft spaces. Features exposed brick walls, concrete or polished wood floors, and metal architectural elements. The design includes leather furniture with worn patinas, reclaimed wood coffee tables, and factory-inspired lighting fixtures. Industrial elements feature visible ductwork, steel-framed windows, and Edison bulb chandeliers. Modern comforts include plush seating, area rugs for warmth, and modern technology integration. The raw, authentic aesthetic is balanced with comfortable textiles and greenery. Open layouts with high ceilings create dramatic spaces. Ideal for urban dwellers who appreciate edgy, authentic design with character and history." },
      { imageSrc: "/living room/download (5).jpg", title: "Traditional Classic Living Room", description: "Celebrate timeless elegance in this traditional living room that honors classic design principles. Features formal furniture arrangements, rich wood finishes, and sophisticated upholstery in quality fabrics. The design includes crown molding, wainscoting, and architectural details that add character. Traditional elements feature symmetrical layouts, paired seating, and classic coffee tables. Premium appointments include antique or antique-style pieces, oriental rugs, crystal chandeliers, and formal window treatments with swags and jabots. Color schemes favor rich jewel tones or elegant neutrals. The refined atmosphere creates spaces for formal entertaining and comfortable family gatherings. Perfect for those who appreciate enduring classical beauty and gracious living." },
      { imageSrc: "/living room/download.jpg", title: "Coastal Breeze Beach House Living", description: "Bring oceanside tranquility home with this coastal-inspired living room. Features light and airy color palette of whites, blues, and sandy neutrals that evoke beach living. The design includes natural materials like rattan, jute, and weathered wood, slipcovered furniture for relaxed elegance, and nautical-inspired accents. Coastal elements feature striped patterns, seashell collections, coral decorations, and ocean artwork. Modern conveniences include ceiling fans, moisture-resistant fabrics, and easy-care surfaces. Large windows or glass doors maximize views and natural light. The casual, breezy atmosphere promotes relaxation and informal entertaining. Ideal for coastal homes or anyone wanting to capture beach house charm and laid-back luxury." },
      { imageSrc: "/living room/lv.jpg", title: "Maximalist Eclectic Living Room", description: "Express your personality boldly in this maximalist living room that celebrates color, pattern, and collected treasures. Features mix-and-match furniture from different eras and styles, layered textiles with various patterns, and walls filled with art and mirrors. The design includes bold color combinations, statement lighting fixtures, and abundant decorative objects. Maximalist elements feature gallery walls, patterned rugs on patterned floors, mixed metallics, and diverse textures. Modern functionality ensures comfortable seating, adequate lighting, and practical storage hidden within the abundance. The vibrant, personal atmosphere creates conversation-starting spaces full of character. Perfect for creative spirits who love to surround themselves with beautiful things and aren't afraid of color and pattern." },
    ],
    kitchen: [
      { imageSrc: "/kitchen/kitchen1.jpg", title: "Pristine Pearl White U-Shaped Modular Kitchen", category: "L-Shaped", description: "Immerse yourself in the timeless elegance of our Pristine Pearl White kitchen design. This sophisticated L-shaped layout features premium gloss-finish cabinets with anti-fingerprint coating, complemented by sleek quartz countertops that resist stains and scratches. The kitchen includes state-of-the-art built-in appliances, touch-activated lighting under cabinets, and innovative soft-close drawer systems. With optimized storage solutions including pull-out organizers, corner carousels, and deep drawers, every inch is designed for maximum functionality. The bright white palette creates an illusion of spaciousness while maintaining a contemporary aesthetic. Perfect for modern homes seeking a clean, minimalist yet luxurious cooking environment." },
      { imageSrc: "/kitchen/kitchen2.jpg", title: "Warm Ecru Elegance L-Shaped Modular Kitchen", category: "L-Shaped", description: "Discover the warmth and sophistication of our Ecru Elegance series, where traditional charm meets modern functionality. This L-shaped masterpiece showcases premium matte-finish cabinetry in soothing ecru tones, paired with engineered stone countertops that offer superior durability. Features include integrated LED strip lighting, premium stainless steel appliances, and innovative space-saving solutions like vertical pull-outs and corner optimizers. The kitchen incorporates smart ventilation systems and easy-to-maintain surfaces. The warm color palette creates an inviting atmosphere perfect for family gatherings while the ergonomic design ensures efficient workflow during meal preparation. An ideal choice for those who appreciate understated luxury and timeless design." },
      { imageSrc: "/kitchen/kitchen3.jpg", title: "Gainsboro Grace U-Shaped Island Kitchen", category: "U-shaped Island", description: "Experience culinary excellence in our Gainsboro Grace kitchen, featuring a stunning U-shaped layout with a magnificent central island. This premium design showcases soft gray-toned cabinetry with brushed nickel hardware, complemented by luxurious granite or quartz island countertops perfect for both food preparation and casual dining. The spacious layout includes premium built-in appliances, dedicated zones for cooking, cleaning, and storage, plus overhead cabinets with glass inserts for display. The island features integrated breakfast bar seating with comfortable bar stools, under-counter storage, and ambient pendant lighting. Smart organizational systems include spice pull-outs, cutlery dividers, and pantry units. The calming gainsboro palette creates a serene cooking environment that's both elegant and practical." },
      { imageSrc: "/kitchen/kitchen4.jpg", title: "Coastal Breeze Straight Island Kitchen", category: "Straight Island", description: "Bring the serenity of coastal living into your home with our Coastal Breeze kitchen design. This light and airy straight island layout features crisp white or light blue cabinetry reminiscent of seaside cottages, paired with natural wood accents and marble-effect countertops. The sleek straight island provides generous prep space while maintaining an open, flowing layout ideal for entertaining. Premium features include soft-close shaker-style cabinets, farmhouse-style sink, chrome fixtures, and open shelving for displaying decorative items. The kitchen incorporates natural light optimization with strategically placed windows and reflective surfaces. Beach-inspired touches like glass cabinet doors, rope handles, and light fixtures create a relaxed yet refined atmosphere perfect for modern coastal homes." },
      { imageSrc: "/kitchen/kitchen5.jpg", title: "Zen Serenity L-Shaped Island Kitchen", category: "L-Shaped Island", description: "Embrace minimalist luxury with our Zen Serenity kitchen, where form meets function in perfect harmony. This contemporary L-shaped design with central island embodies the essence of modern minimalism featuring handleless push-to-open cabinets, seamless surfaces, and a neutral color palette that promotes tranquility. Premium materials include anti-scratch acrylic finishes, waterfall-edge quartz countertops, and integrated appliances that disappear into the design. The island serves as both workspace and dining area with hidden storage compartments and wireless charging stations. Advanced features include touch-control induction cooktops, silent exhaust systems, and motion-sensor cabinet lighting. The clutter-free design incorporates concealed storage solutions ensuring countertops remain pristine. Perfect for those seeking a peaceful, sophisticated cooking sanctuary." },
      { imageSrc: "/kitchen/kitchen6.png", title: "Urban Contemporary U-Shaped Kitchen", category: "U-Shaped", description: "Step into the future of kitchen design with our Urban Contemporary series. This striking U-shaped layout showcases bold contrasts with high-gloss dark cabinetry paired against light countertops and backsplashes. The kitchen features cutting-edge technology including smart appliances controllable via app, built-in coffee stations, wine coolers, and double ovens for serious cooking. Premium finishes include stainless steel accents, geometric tile patterns, and designer pendant lighting. Innovative storage includes tall pantry units with pull-out shelves, appliance garages, and dedicated zones for different activities. The U-shaped configuration maximizes counter space and creates an efficient work triangle. Ideal for urban professionals who demand both aesthetics and peak performance in their culinary space." },
      { imageSrc: "/kitchen/kitchen7.jpg", title: "Royal Mahogany Parallel Luxury Kitchen", category: "Parallel", description: "Indulge in opulence with our Royal Mahogany parallel kitchen, designed for connoisseurs of fine living. This luxurious design features rich mahogany or walnut wood veneers with hand-carved details, complemented by exotic granite or marble countertops with book-matched patterns. The parallel layout offers dual-zone functionality with separate prep and cooking areas on opposite walls. Premium appointments include professional-grade gas ranges, built-in wine refrigerators, custom range hoods with designer detailing, and glass-front upper cabinets with interior lighting. Features crown molding, decorative corbels, and antique brass or bronze hardware. The kitchen includes a butler's pantry, spice rack pull-outs, and plate organizers. This masterpiece kitchen is perfect for entertaining and impressing guests with uncompromising elegance." },
      { imageSrc: "/kitchen/kitchen8.jpg", title: "Heritage Classic L-Shaped Kitchen", category: "L-Shaped", description: "Celebrate timeless beauty with our Heritage Classic kitchen that seamlessly blends traditional charm with modern convenience. This L-shaped design features solid wood cabinetry with raised panel doors, classic crown molding, and decorative valances that evoke old-world craftsmanship. The kitchen showcases premium elements like farmhouse apron-front sinks, vintage-inspired faucets with cross handles, and traditional subway tile backsplashes. Modern conveniences include energy-efficient appliances disguised with cabinet panels, pull-out trash systems, and lazy Susan corner units. Natural stone or butcher block countertops add authentic character. Features include plate racks, open shelving with decorative brackets, and under-cabinet task lighting. The warm, inviting design creates a cozy atmosphere perfect for families who appreciate enduring style and traditional values." },
      { imageSrc: "/kitchen/kitchen9.jpg", title: "Compact Genius Straight Kitchen", category: "Straight", description: "Maximize every square inch with our Compact Genius kitchen, intelligently designed for modern urban apartments and smaller homes. This straight-line layout proves that compact doesn't mean compromising on style or functionality. Features include multi-functional cabinets with internal organizers, wall-mounted magnetic knife strips, fold-down tables, and vertical storage solutions that utilize full ceiling height. The kitchen incorporates slim-line appliances, including apartment-sized dishwashers and combination microwave-convection ovens. Clever innovations include pull-out pantries, toe-kick drawers, and wall-mounted pot racks. Light colors and reflective surfaces create visual spaciousness while under-cabinet and in-cabinet LED lighting ensures excellent visibility. Every element is thoughtfully placed for ergonomic efficiency. Perfect for singles, couples, or small families seeking a fully-equipped kitchen without sacrificing living space." },
      { imageSrc: "/kitchen/kitchen10.png", title: "Opulent Platinum Premium Kitchen", category: "Island", description: "Experience the pinnacle of luxury kitchen design with our Opulent Platinum series. This stunning premium kitchen features imported Italian marble countertops, custom-crafted cabinetry with soft-close mechanisms, and top-of-the-line integrated appliances from leading European brands. The spacious island design provides ample workspace for gourmet cooking and entertaining. Premium finishes include brushed gold hardware, ambient LED lighting, and smart home integration. Every detail has been meticulously crafted to deliver an unparalleled culinary experience. Perfect for discerning homeowners who appreciate the finest things in life and demand nothing but excellence in their living spaces." },
    ],
    bedroom: [
      { imageSrc: "/bedroom/bedroom.jpg", title: "Luxe Contemporary Master Suite", description: "Experience ultimate comfort in this luxurious contemporary master bedroom. Features a plush upholstered king-size bed with designer bedding, custom built-in wardrobes with LED lighting, and floating nightstands with integrated charging stations. The design includes ambient layered lighting with dimmers, blackout curtains for optimal sleep, and premium hardwood or engineered flooring. Modern conveniences feature smart home controls for lighting and temperature, hidden cable management, and ample storage solutions. Neutral tones with accent colors create a sophisticated yet restful atmosphere. Perfect for homeowners seeking hotel-quality comfort and contemporary elegance in their private retreat." },
      { imageSrc: "/bedroom/bedroom1.jpg", title: "Scandinavian Minimalist Haven", description: "Embrace Nordic simplicity with this beautiful Scandinavian-inspired bedroom. Features light wood furniture, clean lines, and a neutral color palette dominated by whites, grays, and natural wood tones. The design includes platform bed with simple headboard, floating shelves, and minimal decorative elements that promote tranquility. Natural materials like linen bedding, wool rugs, and wooden accents add warmth. Large windows maximize natural light while simple roller blinds provide privacy. Storage solutions include under-bed drawers and wall-mounted organizers. The uncluttered, functional design creates a peaceful sanctuary perfect for rest and rejuvenation. Ideal for those who appreciate clean, timeless Scandinavian aesthetics." },
      { imageSrc: "/bedroom/bedroom2.webp", title: "Romantic French Provincial Bedroom", description: "Step into elegance with this romantic French Provincial bedroom that exudes timeless charm. Features an ornate upholstered bed with tufted headboard, antique-inspired furniture with curved details, and soft pastel color schemes. The design includes crystal chandelier, decorative molding, and vintage-style mirrors that add sophistication. Premium elements feature luxury bedding with ruffles and embroidery, plush area rugs, and silk or velvet draperies. Modern updates include hidden storage, efficient lighting, and contemporary comfort within traditional aesthetics. The feminine, romantic atmosphere creates a dreamy retreat. Perfect for those who love classic French elegance and sophisticated luxury." },
      { imageSrc: "/bedroom/bedroom3.jpg", title: "Modern Industrial Loft Bedroom", description: "Make a bold statement with this industrial-chic loft bedroom featuring exposed brick walls, metal accents, and raw materials. The design includes a low-profile platform bed, metal pipe shelving, and Edison bulb lighting fixtures. Features concrete or polished wood floors, open closet systems with metal frames, and minimalist furniture with clean lines. Modern conveniences include smart lighting controls, built-in USB ports, and efficient climate control. The edgy aesthetic is balanced with soft textiles like plush bedding and area rugs. Large windows with metal frames flood the space with natural light. Ideal for urban dwellers who appreciate authentic, raw design with modern comfort." },
      { imageSrc: "/bedroom/bedroom4.webp", title: "Coastal Serenity Beach House Bedroom", description: "Bring seaside tranquility into your home with this coastal-inspired bedroom. Features light blue and white color palette, weathered wood furniture, and nautical accents that evoke beachside living. The design includes shiplap accent walls, rope details, and natural fiber rugs. Premium elements feature crisp white linens, gauzy curtains that flutter in the breeze, and sea-inspired artwork. Modern amenities include ceiling fans, efficient ventilation, and moisture-resistant materials. The layout maximizes natural light through large windows with ocean or garden views. The relaxed, breezy atmosphere promotes restful sleep. Perfect for coastal homes or anyone wanting to capture beach house charm and relaxation." },
      { imageSrc: "/bedroom/bedroom5.jpg", title: "Traditional Elegance Master Bedroom", description: "Celebrate timeless beauty with this traditional master bedroom that combines classic design with modern comfort. Features rich wood furniture with carved details, traditional four-poster or sleigh bed, and sophisticated color schemes. The design includes crown molding, wainscoting, and elegant window treatments with valances. Premium appointments feature high-quality bedding with decorative pillows, area rugs with classic patterns, and traditional table lamps. Modern updates include hidden electronics, efficient lighting, and contemporary mattress technology within classic frames. Storage solutions include armoires, dressers with ornate hardware, and built-in closets. The warm, inviting design creates a comfortable sanctuary perfect for those who appreciate enduring traditional style." },
      { imageSrc: "/bedroom/bedroom6.jpg", title: "Bohemian Eclectic Retreat", description: "Express your creativity in this vibrant bohemian bedroom that celebrates color, pattern, and personal expression. Features mix-and-match textiles, layered rugs, and globally-inspired decor from various cultures. The design includes low platform bed or floor mattress, macramé wall hangings, and hanging plants that bring nature indoors. Colorful elements feature patterned bedding with ethnic prints, tapestries, and vintage finds. Modern functionality includes proper lighting for reading, efficient storage with woven baskets, and comfortable seating areas. The eclectic mix of textures, colors, and patterns creates a cozy, artistic atmosphere. Ideal for free spirits who appreciate unique, personalized spaces filled with character and warmth." },
      { imageSrc: "/bedroom/bedroom7.png", title: "Zen Minimalist Sanctuary", description: "Find ultimate peace in this Zen-inspired minimalist bedroom designed for meditation and rest. Features low platform bed with simple lines, neutral earth tones, and natural materials like bamboo and stone. The design emphasizes empty space, clean surfaces, and carefully curated elements. Premium features include natural fiber bedding, rice paper screens, and subtle indirect lighting. Modern conveniences feature smart controls for ambiance, soundproofing for quietness, and air purification systems. The layout promotes flow and balance with minimal furniture and maximum openness. Incorporates elements like meditation cushions, indoor bonsai, and natural light. Perfect for those seeking tranquility, mindfulness, and a clutter-free sleeping environment." },
      { imageSrc: "/bedroom/bedroom8.jpg", title: "Glamorous Hollywood Regency Suite", description: "Indulge in pure glamour with this Hollywood Regency-inspired bedroom that radiates luxury and sophistication. Features tufted velvet headboard, mirrored furniture, and metallic gold or silver accents throughout. The design includes crystal chandeliers, art deco patterns, and dramatic black and white color schemes with jewel-tone accents. Premium elements feature luxurious bedding with silk or satin, plush carpeting, and floor-to-ceiling mirrors that amplify light and space. Modern amenities include hidden storage, smart lighting with dimming capabilities, and high-end sound systems. The theatrical, opulent design creates a glamorous retreat. Perfect for those who love to make a bold statement and appreciate old Hollywood elegance and drama." },
    ],
    bathroom: [
      { imageSrc: "/bathroom/bathroom.webp", title: "Luxe Spa Master Bathroom", description: "Transform your daily routine into a spa-like experience with this luxurious master bathroom. Features premium Italian marble tiles, a freestanding soaking tub, rainfall shower with body jets, and heated floors. The design includes floating double vanities with LED-backlit mirrors, soft-close drawers with smart organizational inserts, and ambient lighting that creates a serene atmosphere. Premium fixtures in brushed gold or chrome finish add elegance, while the neutral color palette of whites, grays, and natural stone creates a timeless look. Perfect for homeowners seeking a personal wellness retreat." },
      { imageSrc: "/bathroom/bathroom1.webp", title: "Modern Minimalist Sanctuary", description: "Embrace clean lines and simplicity in this modern minimalist bathroom. The design features wall-mounted vanities creating a floating effect, frameless glass shower enclosure, and seamless large-format porcelain tiles that minimize grout lines. Includes concealed storage solutions, touch-free faucets, and integrated LED lighting strips. The monochromatic color scheme with subtle texture variations creates visual interest while maintaining serenity. Features include anti-fog mirror technology, underfloor heating, and eco-friendly water-saving fixtures. Ideal for contemporary homes that value both aesthetics and functionality." },
      { imageSrc: "/bathroom/bathroom2.jpg", title: "Classic Victorian Elegance", description: "Step back in time with this Victorian-inspired bathroom that combines old-world charm with modern convenience. Features include a clawfoot bathtub with antique brass fixtures, pedestal sink with ornate detailing, and vintage-style subway tiles with decorative borders. The design incorporates crown molding, wainscoting, and classic hexagonal floor tiles. Modern amenities include concealed plumbing, efficient ventilation, and updated lighting while maintaining period authenticity. Rich wood tones and crystal chandelier add warmth and sophistication. Perfect for heritage homes or those who appreciate timeless classical design." },
      { imageSrc: "/bathroom/bathroom3.jpg", title: "Contemporary Zen Retreat", description: "Find peace and tranquility in this Zen-inspired contemporary bathroom. The design features natural materials including teak wood accents, river stone flooring, and bamboo elements. Includes a deep Japanese-style soaking tub, walk-in rain shower with pebble floor, and minimalist floating vanity. Natural light is maximized through frosted glass and skylights. Features include waterfall faucets, live plants, and neutral earth tones that promote relaxation. The layout emphasizes clean lines, uncluttered spaces, and natural textures. Ideal for those seeking a meditative bathing experience and connection with nature." },
      { imageSrc: "/bathroom/bathroom4.webp", title: "Industrial Chic Loft Bathroom", description: "Make a bold statement with this industrial-style bathroom featuring exposed brick walls, concrete countertops, and matte black fixtures. The design includes a walk-in glass-enclosed shower, Edison bulb lighting, and metal-framed mirrors. Features raw materials like weathered wood shelving, subway tiles with dark grout, and vintage-inspired faucets. Modern conveniences include heated towel racks, smart ventilation, and water-efficient fixtures. The edgy aesthetic is softened with plush textiles and greenery. Perfect for urban lofts and those who appreciate raw, authentic design with modern comfort." },
      { imageSrc: "/bathroom/bathroom5.avif", title: "Coastal Breezy Beach House Bath", description: "Bring the serenity of the ocean into your home with this coastal-inspired bathroom. Features light blue and white color palette, shiplap walls, and weathered wood accents. Includes a spacious walk-in shower with pebble floor reminiscent of beach stones, nautical-themed hardware, and plenty of natural light. Design elements include seashell motifs, rope details, and glass vessel sinks. Modern amenities feature water-resistant wood-look tiles, efficient lighting, and storage solutions. The airy, open design creates a relaxing beach house atmosphere. Perfect for coastal homes or anyone wanting to capture seaside tranquility." },
      { imageSrc: "/bathroom/bathroom6.webp", title: "Glamorous Hollywood Regency Bath", description: "Indulge in pure glamour with this Hollywood Regency-inspired bathroom that exudes luxury and sophistication. Features include crystal chandeliers, mirrored surfaces, and metallic gold or silver accents. The design showcases a stunning freestanding tub as the centerpiece, marble countertops with waterfall edges, and art deco-inspired geometric patterns. Premium elements include velvet upholstered seating, ornate mirrors with decorative frames, and high-end fixtures. The dramatic black and white color scheme with metallic highlights creates timeless elegance. Perfect for those who love to make a statement and appreciate opulent, theatrical design." },
      { imageSrc: "/bathroom/bathroom7.jpg", title: "Scandinavian Simplicity Bathroom", description: "Experience the essence of Scandinavian design in this beautifully simple yet functional bathroom. Features include light wood cabinetry, white subway tiles, and minimalist chrome fixtures. The design emphasizes natural light with large windows, simple lines, and uncluttered surfaces. Includes efficient storage solutions hidden behind sleek cabinet doors, geometric black and white floor tiles, and greenery for a fresh feel. Modern conveniences feature energy-efficient lighting, eco-friendly materials, and water-saving fixtures. The bright, airy space promotes cleanliness and calm. Ideal for those who appreciate functional beauty and Nordic-inspired design." },
      { imageSrc: "/bathroom/bathroom8.jpg", title: "Serene Marble Luxury Bathroom", description: "Indulge in sophisticated luxury with this stunning marble bathroom featuring premium natural stone throughout. The design showcases floor-to-ceiling marble walls with beautiful veining patterns, creating a spa-like atmosphere of refined elegance. Features include a spacious walk-in shower with frameless glass enclosure, rainfall showerhead, and body jets. The floating vanity with integrated sink offers clean lines and ample storage, complemented by designer chrome fixtures and a large illuminated mirror. Ambient LED lighting enhances the marble's natural beauty while creating a warm, inviting glow. Modern conveniences include heated floors, smart temperature controls, and high-end ventilation systems. The neutral palette of whites and grays exudes timeless sophistication, perfect for those who appreciate understated luxury and hotel-quality comfort in their private sanctuary." },
    ],
    wardrobe: [
      { imageSrc: "/wardrobe/12 Wardrobe Design Bedroom Modern Luxury Ideas for___.jpg", title: "Modern Luxury Wardrobe Collection", description: "Experience ultimate organization and luxury with this modern wardrobe design featuring sleek handleless doors, premium finishes, and innovative storage solutions. The design includes floor-to-ceiling cabinetry that maximizes vertical space, soft-close mechanisms, and LED interior lighting for easy visibility. Premium materials feature high-gloss laminates, mirror panels, and integrated accessories like pull-out drawers, jewelry organizers, and shoe racks. Modern conveniences include smart lighting sensors, climate control for delicate garments, and customizable shelving systems. The contemporary aesthetic with clean lines creates a sophisticated bedroom focal point. Perfect for those seeking a luxury boutique experience at home with ample storage and impeccable organization." },
      { imageSrc: "/wardrobe/Add Touch Of Elegance To Your Bedroom With This Wardrobe Collection.jpg", title: "Elegant Bedroom Wardrobe Collection", description: "Add a touch of timeless elegance to your bedroom with this sophisticated wardrobe collection. Features classic design elements including raised panel doors, ornate handles in antique finishes, and quality wood veneers. The design includes multiple hanging sections for different garment lengths, spacious drawers with velvet lining, and open shelving for folded items. Premium appointments feature soft-close hinges, adjustable shelves, and integrated tie and belt racks. Traditional craftsmanship meets modern functionality with proper ventilation, interior lighting, and modular configurations. The refined aesthetic complements both traditional and transitional bedroom styles. Ideal for those who appreciate classical elegance combined with practical storage solutions." },
      { imageSrc: "/wardrobe/download (1).jpg", title: "Contemporary Sliding Door Wardrobe", description: "Maximize space efficiency with this contemporary sliding door wardrobe perfect for modern bedrooms. Features smooth-gliding door systems that save floor space, clean minimalist profiles, and quality materials. The design includes versatile interior layouts with hanging rods at multiple heights, pull-out drawers, and modular shelf systems. Modern elements feature soft-close mechanisms, full-length mirrors on doors, and optional LED lighting. Premium finishes available in matte, gloss, or wood grain laminates to match any decor. The space-saving design makes it ideal for smaller bedrooms while providing ample storage. Perfect for contemporary homes seeking functionality without compromising on style." },
      { imageSrc: "/wardrobe/download (2).jpg", title: "Walk-In Closet Wardrobe System", description: "Transform your bedroom into a luxury boutique with this walk-in closet wardrobe system. Features comprehensive organization including double hanging sections, dedicated shoe storage, accessory drawers, and display shelving. The design includes a central island with jewelry storage, pull-out trouser racks, and dedicated handbag shelves. Premium appointments feature velvet-lined drawers, LED strip lighting throughout, full-length mirrors, and optional seating area. Modern conveniences include motion-sensor lighting, climate control options, and customizable layouts. The boutique-like atmosphere with elegant finishes creates a dressing room experience. Ideal for luxury homes with space for dedicated walk-in closets and extensive wardrobes." },
      { imageSrc: "/wardrobe/download.jpg", title: "Minimalist Scandinavian Wardrobe", description: "Embrace Nordic simplicity with this minimalist Scandinavian wardrobe that combines beauty with function. Features light wood construction, simple clean lines, and handleless push-to-open doors. The design emphasizes quality materials, efficient use of space, and thoughtful organization. Includes adjustable hanging rods, pull-out drawers with fabric inserts, and open shelving for display. Scandinavian elements feature natural wood finishes, white interiors, and geometric simplicity. Modern functionality includes soft-close mechanisms, modular components, and sustainable materials. The understated design creates calm, organized spaces. Perfect for those who appreciate Scandinavian design principles of simplicity, functionality, and natural materials." },
      { imageSrc: "/wardrobe/Laundry Room Cabinets With Hanging Rod, Laundry Room Cabinets Organization.jpg", title: "Multi-Purpose Storage Wardrobe System", description: "Maximize versatility with this multi-purpose storage wardrobe system featuring hanging rods, cabinets, and organizational solutions. The design includes upper cabinets for seasonal storage, lower cabinets for shoes and accessories, and central hanging sections for daily wear. Features include pull-out laundry hampers, ironing board storage, and dedicated sections for different garment types. Premium organization includes adjustable shelving, drawer dividers, and specialized racks. Modern conveniences feature soft-close doors and drawers, ventilated sections, and optional lighting. The comprehensive design addresses all storage needs efficiently. Ideal for organized homes seeking all-in-one storage solutions that keep everything accessible yet hidden." },
      { imageSrc: "/wardrobe/Unlocking Style 12 Brilliant Wardrobe Ideas for Your Bedroom in 2024.jpg", title: "Brilliant Modern Wardrobe Design", description: "Unlock brilliant style with this cutting-edge modern wardrobe design featuring innovative storage solutions and contemporary aesthetics. Features include asymmetric door designs, mixed materials combining wood and glass, and smart internal configurations. The design incorporates open display sections, concealed storage, and flexible hanging options. Premium elements feature integrated LED lighting, mirror panels, and high-quality hardware. Modern innovations include smart sensors, modular accessories, and customizable layouts. The striking design becomes a bedroom statement piece while providing exceptional functionality. Perfect for style-conscious homeowners seeking wardrobes that are both beautiful and brilliantly organized." },
      { imageSrc: "/wardrobe/Wooden Cupboard Design.jpg", title: "Classic Wooden Cupboard Design", description: "Celebrate traditional craftsmanship with this classic wooden cupboard wardrobe design featuring solid wood construction and timeless appeal. Features include traditional joinery techniques, raised panel doors, and quality wood finishes in rich tones. The design showcases detailed molding, classic hardware, and sturdy construction built to last generations. Premium appointments include cedar-lined drawers for delicate items, brass or bronze hardware, and hand-finished surfaces. Traditional elements feature symmetrical design, proper proportions, and authentic materials. Modern updates include soft-close mechanisms while maintaining classic aesthetics. The enduring design adds warmth and character to bedrooms. Ideal for traditional homes or those who appreciate fine woodworking and timeless furniture design." },
    ],
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <section className="py-12 bg-accent">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="font-heading font-bold text-4xl md:text-5xl mb-4">
            Interior Design Gallery
          </h1>
          <p className="text-muted-foreground text-lg max-w-3xl mx-auto">
            Browse through our extensive collection of beautifully designed spaces. Get inspired for your next home interior project.
          </p>
        </div>
      </section>

      <section className="py-16 bg-background">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <div className="flex justify-center mb-12">
              <TabsList className="grid grid-cols-6 w-full max-w-4xl">
                <TabsTrigger value="all" data-testid="tab-all">All Designs</TabsTrigger>
                <TabsTrigger value="living" data-testid="tab-living">Living Room</TabsTrigger>
                <TabsTrigger value="kitchen" data-testid="tab-kitchen">Kitchen</TabsTrigger>
                <TabsTrigger value="bedroom" data-testid="tab-bedroom">Bedroom</TabsTrigger>
                <TabsTrigger value="bathroom" data-testid="tab-bathroom">Bathroom</TabsTrigger>
                <TabsTrigger value="wardrobe" data-testid="tab-wardrobe">Wardrobe</TabsTrigger>
              </TabsList>
            </div>

            <TabsContent value="all">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.all.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    category={design.category}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>

            <TabsContent value="living">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.living.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>

            <TabsContent value="kitchen">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.kitchen.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    category={design.category}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>

            <TabsContent value="bedroom">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.bedroom.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>

            <TabsContent value="bathroom">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.bathroom.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>

            <TabsContent value="wardrobe">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {designs.wardrobe.map((design, index) => (
                  <DesignCard
                    key={index}
                    imageSrc={design.imageSrc}
                    title={design.title}
                    onClick={() => setSelectedDesign(design)}
                  />
                ))}
              </div>
            </TabsContent>
          </Tabs>

          <div className="text-center mt-12">
            <Button
              size="lg"
              onClick={() => setLocation("/consultation")}
              data-testid="button-gallery-cta"
            >
              Book Free Design Session
            </Button>
          </div>
        </div>
      </section>

      <Dialog open={!!selectedDesign} onOpenChange={() => setSelectedDesign(null)}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          {selectedDesign && (
            <>
              <DialogHeader>
                <DialogTitle className="text-2xl font-bold pr-8">
                  {selectedDesign.title}
                </DialogTitle>
                {selectedDesign.category && (
                  <Badge variant="secondary" className="w-fit mt-2">
                    {selectedDesign.category}
                  </Badge>
                )}
              </DialogHeader>
              
              <div className="space-y-6">
                <div className="relative aspect-[4/3] w-full max-w-2xl mx-auto overflow-hidden rounded-lg">
                  <img
                    src={selectedDesign.imageSrc}
                    alt={selectedDesign.title}
                    className="w-full h-full object-cover"
                  />
                </div>
                
                <div className="space-y-4">
                  <div>
                    <h3 className="font-semibold text-lg mb-2">About This Design</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      {selectedDesign.description || "A beautiful interior design that combines functionality with aesthetic appeal. Our expert designers have carefully crafted this space to meet modern living standards while maintaining timeless elegance."}
                    </p>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t">
                    <div className="space-y-1">
                      <p className="text-sm font-semibold">Style</p>
                      <p className="text-sm text-muted-foreground">Modern Contemporary</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-semibold">Estimated Timeline</p>
                      <p className="text-sm text-muted-foreground">45-60 Days</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-semibold">Customizable</p>
                      <p className="text-sm text-muted-foreground">Yes, Fully Customizable</p>
                    </div>
                  </div>
                  
                  <div className="flex gap-3 pt-4">
                    <Button 
                      onClick={() => {
                        setSelectedDesign(null);
                        setLocation("/consultation");
                      }}
                      className="flex-1"
                    >
                      Book Free Consultation
                    </Button>
                    <Button 
                      variant="outline"
                      onClick={() => setLocation("/calculators")}
                      className="flex-1"
                    >
                      Get Price Estimate
                    </Button>
                  </div>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      <FloatingChat />
      <Footer />
    </div>
  );
}
